name: klmd

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: sudo apt-get install libusb-1.0-0-dev
    - name: Build
      working-directory: klmd/
      run: cargo build --verbose
    - name: Upload debug build to GitHub
      uses: actions/upload-artifact@v3
      with:
        name: klmd
        path: klmd/target/debug/klmd
